services:
  # PostgreSQL
  odoo-postgresql:
    image: postgres:17
    container_name: odoo-postgresql
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo_food_supply_chain
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data  # Sử dụng thư mục trên host
    ports:
      - "5432:5432"
    networks:
      - odoo-network
    restart: unless-stopped

  # Odoo
  odoo:
    image: odoo:18.0
    container_name: odoo
    depends_on:
      - odoo-postgresql
    ports:
      - "8069:8069"
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo-network
    restart: unless-stopped

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - odoo-network
    restart: unless-stopped

networks:
  odoo-network:
    driver: bridge
